name: PHP Workflow

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*' # Matches version tags like v1.0.0
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v3
      with:
        php-version: '8.1' # or your preferred PHP version

    - name: Install dependencies
      run: composer install

    - name: Run tests
      run: vendor/bin/phpunit # Adjust if you use a different test script

    - name: Run PHP CodeSniffer
      run: vendor/bin/phpcs # Adjust if you use a different linter

    - name: Run PHP-CS-Fixer
      run: vendor/bin/php-cs-fixer fix --dry-run --diff # Adjust if you use a different formatter

    - name: Build
      run: |
        # Add any build steps if needed
        # For example, if you have a custom build script, run it here

    - name: Publish to Packagist
      if: startsWith(github.ref, 'refs/tags/v') # Only run this step for version tags
      run: |
        composer config --global http-basic.repo.packagist.com ${{ secrets.PACKAGIST_USERNAME }} ${{ secrets.PACKAGIST_TOKEN }}
        composer publish
      env:
        PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
